name: blueberry_flutter_template
description: "flutter-template"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Splash & Icon
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  # Core
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0

  # Freezed
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0

  # Firebase
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  firebase_analytics: ^11.1.0
  cloud_firestore: ^5.0.2

  # UI
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  pinput: ^4.0.0

  # Service
  dart_openai: ^5.1.0
  bootpay: ^4.9.7

  # Social Login
  sign_in_with_apple: ^6.1.1
  google_sign_in: ^6.2.1

  # Utils
  app_links: ^6.1.3
  photo_manager: ^3.2.0
  image_picker: ^1.1.0

  # Profile Upload
  camera: ^0.11.0+1
  webview_flutter: ^4.8.0
  transparent_image: ^2.0.1
  photo_manager_image_provider: ^2.1.1

  # Match
  flutter_card_swiper: ^7.0.1

  # FCM
  permission_handler: ^11.3.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  flutter_secure_storage: ^4.2.1

  # Delete account
  easy_engine: ^0.0.4
  cloud_functions: ^5.0.2

  # Lints
  flutter_lints: ^3.0.0
  flutter_gen: ^5.6.0
  
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/600x400/
    - assets/300x420/
    - assets/700x150/
    - assets/logo/
    - assets/login_page_images/

# Run Commands to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/logo_4.png
  color_dark: "#1a1a1a"
  image_dark: assets/logo/logo_4.png

  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/logo/logo_4.png
    icon_background_color_dark: "#1a1a1a"
    image_dark: assets/logo/logo_4.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_5.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo_5.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
